version: '3'

env:
  GO: go
  GOBUILD: '{{.GO}} build'
  GORUN: '{{.GO}} run'
  TEMPL: templ
  TEMPO: tempo

tasks:
  live:templ:
    desc: Run templ generation in watch mode
    internal: true
    cmds:
      - templ generate --watch --proxy="http://localhost:3300" --open-browser=true

  live:server:
    desc: Run air to detect file changes, re-build and re-run the server
    internal: true
    cmds:
      - |
        go run github.com/air-verse/air@v1.61.7 \
          --build.cmd "go build -o tmp/bin/main" \
          --build.bin "tmp/bin/main" \
          --build.delay "100" \
          --build.exclude_dir "node_modules" \
          --build.include_ext "go" \
          --build.stop_on_error "false" \
          --misc.clean_on_exit true

  live:sync:
    desc: Watch for asset changes and reload browser via templ proxy
    internal: true
    cmds:
      - |
        go run github.com/air-verse/air@v1.61.7 \
          --build.cmd "tempo sync && templ generate -notify-proxy" \
          --build.bin "true" \
          --build.delay "100" \
          --build.exclude_dir "" \
          --build.include_dir "assets" \
          --build.include_ext "js,css"

  dev:
    desc: Run the dev server with live reload
    deps: [live:templ, live:server, live:sync]

  build:
    desc: Build for production with minified asset files
    cmds:
      - tempo sync --prod
      - templ fmt .
      - templ generate
      - go build -o tmp/bin/tempo-demo
