// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.856
package variants

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

var buttonOutlineVariantHandler = templ.NewOnceHandle()

func VariantOutline() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style type=\"text/css\">\n/* [tempo] BEGIN - Do not edit! This section is auto-generated. */\n@layer components{.btn[data-variant=outline]{--btn-color: var(--btn-outline-color);--btn-color-hover: var(--btn-outline-color-hover);--btn-bg: var(--btn-outline-bg);--btn-bg-hover: var(--btn-outline-bg-hover);--btn-border: var(--btn-outline-border)}:root{--btn-outline-color: oklch(.518 .253 323.949);--btn-outline-color-hover: oklch(.452 .211 324.591);--btn-outline-bg: transparent;--btn-outline-bg-hover: oklch(.952 .037 318.852);--btn-outline-border: oklch(.74 .238 322.16)}html.light,html[data-theme=light],body.light{--btn-outline-color: oklch(.518 .253 323.949);--btn-outline-color-hover: oklch(.452 .211 324.591);--btn-outline-bg: transparent;--btn-outline-bg-hover: oklch(.952 .037 318.852);--btn-outline-border: oklch(.74 .238 322.16)}html.dark,html[data-theme=dark],body.dark{--btn-outline-color: oklch(.833 .145 321.434);--btn-outline-color-hover: oklch(.952 .037 318.852);--btn-outline-bg: transparent;--btn-outline-bg-hover: oklch(.667 .295 322.15 / .5);--btn-outline-border: oklch(.667 .295 322.15)}@media (prefers-color-scheme: dark){:root{--btn-outline-color: oklch(.833 .145 321.434);--btn-outline-color-hover: oklch(.952 .037 318.852);--btn-outline-bg: transparent;--btn-outline-bg-hover: oklch(.667 .295 322.15 / .5);--btn-outline-border: oklch(.667 .295 322.15)}}}\n\n/* [tempo] END */\n</style>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = buttonOutlineVariantHandler.Once().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
